### ISSUE TITLE
Twisted and Monads

### ISSUE THREAD

**Issue by bao-qian** [jml/code.mumak.net#4]
Hi,
I found one of your post is interesting, https://jml.io/2009/07/twisted-monads.html .

but I can't find the slide http://static.mumak.net/Twisted-Monads.pdf anywhere on the internet.

could you share a copy of this slide?

thanks.

**Comment by jml** [comment]
Here it is: [Twisted-Monads.pdf](https://github.com/jml/code.mumak.net/files/1666185/Twisted-Monads.pdf)

**Comment by jml** [comment]
Now also available at the old URL: https://static.mumak.net/Twisted-Monads.pdf
